version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-sender-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - notification-network
    restart: unless-stopped

networks:
  notification-network:
    driver: bridge
